### ISSUE TITLE
Add custom class to div wrapper

### ISSUE THREAD

**Issue by psolom** [bookin/yii2-awesome-bootstrap-checkbox#2]
Hi,
I have to add "class" attribute to div that wraps checkbox/radio.
It would be nice if you add property as "wrapperOptions" to add custom html options to div tag.
Great extension btw.
Thank you.

**Comment by bookin** [comment]
Hi @elastic-od, i added "wrapperOptions", you can test it. Thanks you.

**Comment by psolom** [comment]
so quickly, wow! :)
thanks
