### ISSUE TITLE
Setting checkbox value

### ISSUE THREAD

**Issue by koxu1996** [bookin/yii2-awesome-bootstrap-checkbox#4]
Is there possibility to set checkbox value and uncheck value?

**Comment by bookin** [comment]
If you are using model, you need set value to model's property.
For example:

```
$form = new \yii\widgets\ActiveForm();
$model->test = 1; //checked
$model->test = 0; //uncheked
echo $form->field($model, 'test')->widget(AwesomeCheckbox::classname());
```

Also for:

```
echo \bookin\aws\checkbox\AwesomeCheckbox::widget([
    'model'=>$model,
    'attribute'=>'test',
    //....
]);
```

If you are using just "name", you can use "checked" property:

```
echo \bookin\aws\checkbox\AwesomeCheckbox::widget([
    'name'=>'test',
    'checked'=>true,
   //...
]);
```

**Comment by koxu1996** [comment]
I mean using not boolean values like 5 for unchecked and 7 for checked. I created pull request, which add inputOptions in which user can set these properties.

**Comment by bookin** [comment]
Can you write example how do you see it? How need use it.

**Comment by koxu1996** [comment]
I use it in this way: 

```
echo $form->field($model, 'attribute')->widget(AwesomeCheckbox::classname(), [
    'inputOptions'=>[
        'value'=>5,
        'uncheck'=>7
    ]
]);
```

When user click checkbox I will get value 5, when do not I will get 7

**Comment by bookin** [comment]
I don't understand why need use your $inputOptions, if you can just use $options

```
echo $form->field($model, 'test')->widget(AwesomeCheckbox::classname(),[
    'options'=>[
        'value'=>5,
        'uncheck'=>7
    ]
]);
```

**Comment by koxu1996** [comment]
Ehh sorry, you are right. Could you add this example to readme? Maybe this will help somebody.

**Comment by bookin** [comment]
You can use all options InputWidget, just do you have some other properties also. (stars as a thank you =) )

**Comment by koxu1996** [comment]
I gave you star for this amazing extension :)  The problem is that it is hard to find in Google.

**Comment by bookin** [comment]
Thanks for the star :) Better find extensions on the packagist.org, and, for example, if you need "Awesome Bootstrap Checkbox", you need search "awesome-bootstrap-checkbox" and add yii2 - "yii2-awesome-bootstrap-checkbox". I think many extensions many extensions can be found in a similar way. When i created this extension, it was be unique extension, and first in the google, i don't know why now "yii2-awesomebootstrapcheckbox" is first )
