### ISSUE TITLE
Problem with not standart input names

### ISSUE THREAD

**Issue by mrfinrod** [bookin/yii2-awesome-bootstrap-checkbox#6]
I have a problem with input names like ids[1]
Example:
`echo $form->field($filterForm, 'ids[' . $propertyItemId . ']')
->widget(AwesomeCheckbox::classname(), [
'style' => AwesomeCheckbox::STYLE_SUCCESS,
])->label($propertyItemName);`
This code does not show any checkbox.
But if I write like this:
`echo AwesomeCheckbox::widget([
                                            'name' => 'FilterForm[ids][' . $propertyItemId . ']',
                                            'style' => AwesomeCheckbox::STYLE_SUCCESS,
                                            'options'=>[
                                                'label' => $propertyItemName,
                                            ],
                                        ]);`
All works fine.
How can I use ActiveForm with such names?

**Comment by bookin** [comment]
Hi, checked, I haven't any problems

`echo $form->field($model, 'test[2]')->widget(AwesomeCheckbox::classname(), [ 'style' => AwesomeCheckbox::STYLE_SUCCESS, ])->label('asdas');`

Check your variables, also check which HTML is generated
